import java.util.*;

public class Driver {

	public static void main(String[] args) {
/*		Scanner in = new Scanner(System.in);
		Team RUS = new Team("Russia");
		Team KSA = new Team("Saudi Arabia");
		Team EGY = new Team("Egypt");
		Team URU = new Team("Uruguay");
		Group A = new Group("A");
		A.AddGroupLeader(RUS);
		A.addTeam(KSA);
		A.addTeam(EGY);
		A.addTeam(URU);
		A.generateMatches();
		A.setMatches();
		A.arrangeStandings();
		A.printStandings();
		Team POR = new Team("Portugal");
		Team ESP = new Team("Spain");
		Team MOR = new Team("Morocco");
		Team IRN = new Team("Iran");
		Group B = new Group("B");
		B.AddGroupLeader(POR);
		B.addTeam(ESP);
		B.addTeam(MOR);
		B.addTeam(IRN);
		B.generateMatches();
		B.setMatches();
		B.arrangeStandings();
		B.printStandings();
		System.out.println("Winner of Group B is: " + B.getGroupWinner());
		System.out.println("RunnerUp of Group B is: " + B.getGroupRunnerUp());
		Team FRA = new Team("France");
		Team AUS = new Team("Australia");
		Team PER = new Team("Peru");
		Team DEN = new Team("Denmark");
		Group C = new Group("C");
		C.AddGroupLeader(FRA);
		C.addTeam(AUS);
		C.addTeam(PER);
		C.addTeam(DEN);
		C.generateMatches();
		C.setMatches();
		C.arrangeStandings();
		C.printStandings();
		Team ARG = new Team("Argentina");
		Team ISL = new Team("Iceland");
		Team CRO = new Team("Croatia");
		Team NIG = new Team("Nigeria");
		Group D = new Group("D");
		D.AddGroupLeader(ARG);
		D.addTeam(ISL);
		D.addTeam(CRO);
		D.addTeam(NIG);
		D.generateMatches();
		D.setMatches();
		D.arrangeStandings();
		D.printStandings();
		Team BRA = new Team("Brazil");
		Team SUI = new Team("Switzerland");
		Team CRC = new Team("Costa Rica");
		Team SRB = new Team("Serbia");
		Group E = new Group("E");
		E.AddGroupLeader(BRA);
		E.addTeam(SUI);
		E.addTeam(CRC);
		E.addTeam(SRB);
		E.generateMatches();
		E.setMatches();
		E.arrangeStandings();
		E.printStandings();
		Team GER = new Team("Germany");
		Team MEX = new Team("Mexico");
		Team SWE = new Team("Sweden");
		Team KOR = new Team("South Korea");
		Group F = new Group("F");
		F.AddGroupLeader(GER);
		F.addTeam(MEX);
		F.addTeam(SWE);
		F.addTeam(KOR);
		F.generateMatches();
		F.setMatches();
		F.arrangeStandings();
		F.printStandings();
		Team BEL = new Team("Belgium");
		Team PAN = new Team("Panama");
		Team TUN = new Team("Tunisia");
		Team ENG = new Team("England");
		Group G = new Group("G");
		G.AddGroupLeader(BEL);
		G.addTeam(PAN);
		G.addTeam(TUN);
		G.addTeam(ENG);
		G.generateMatches();
		G.setMatches();
		G.arrangeStandings();
		Team POL = new Team("Poland");
		Team SEN = new Team("Senegal");
		Team COL = new Team("Colombia");
		Team JPN = new Team("Japan");
		Group H = new Group("H");
		H.AddGroupLeader(POL);
		H.addTeam(SEN);
		H.addTeam(COL);
		H.addTeam(JPN);
		H.generateMatches();
		H.setMatches();
		H.arrangeStandings();
		KnockoutMatch A1B2 = new KnockoutMatch(A.getGroupWinner(),B.getGroupRunnerUp());
		KnockoutMatch C1D2 = new KnockoutMatch(C.getGroupWinner(),D.getGroupRunnerUp());
		KnockoutMatch E1F2 = new KnockoutMatch(E.getGroupWinner(),F.getGroupRunnerUp());
		KnockoutMatch G1H2 = new KnockoutMatch(G.getGroupWinner(),H.getGroupRunnerUp());
		KnockoutMatch B1A2 = new KnockoutMatch(B.getGroupWinner(),A.getGroupRunnerUp());
		KnockoutMatch D1C2 = new KnockoutMatch(D.getGroupWinner(),C.getGroupRunnerUp());
		KnockoutMatch F1E2 = new KnockoutMatch(F.getGroupWinner(),E.getGroupRunnerUp());
		KnockoutMatch H1G2 = new KnockoutMatch(H.getGroupWinner(),G.getGroupRunnerUp());
		System.out.println("Round of 16");
		A1B2.setMatchresult();
		C1D2.setMatchresult();
		E1F2.setMatchresult();
		G1H2.setMatchresult();
		B1A2.setMatchresult();
		D1C2.setMatchresult();
		F1E2.setMatchresult();
		H1G2.setMatchresult();
		KnockoutMatch Q1 = new KnockoutMatch(A1B2.getWinner(),C1D2.getWinner());
		KnockoutMatch Q2 = new KnockoutMatch(E1F2.getWinner(),G1H2.getWinner());
		KnockoutMatch Q3 = new KnockoutMatch(B1A2.getWinner(),D1C2.getWinner());
		KnockoutMatch Q4 = new KnockoutMatch(F1E2.getWinner(),H1G2.getWinner());
		System.out.println("Quarter-Finals");
		Q1.setMatchresult();
		Q2.setMatchresult();
		Q3.setMatchresult();
		Q4.setMatchresult();
		KnockoutMatch Semi1 = new KnockoutMatch(Q1.getWinner(),Q2.getWinner());
		KnockoutMatch Semi2 = new KnockoutMatch(Q3.getWinner(),Q4.getWinner());
		System.out.println("Semi-Finals");
		Semi1.setMatchresult();
		Semi2.setMatchresult();
		KnockoutMatch ThirdPlace = new KnockoutMatch(Semi1.getLoser(),Semi2.getLoser());
		System.out.println("Third-Place Match");
		ThirdPlace.setMatchresult();
		KnockoutMatch Final = new KnockoutMatch(Semi1.getWinner(),Semi2.getWinner());
		System.out.println("2018 FIFA World Cup Final");
		Final.setMatchresult();
		System.out.println("2018 FIFA World Cup Champion: " + Final.getWinner() +" Total Points: " + Final.getWinner().getPoints());
		System.out.println("2018 FIFA World Cup Runner-Up: " + Final.getLoser());
		System.out.println("2018 FIFA World Cup Third Place: " + ThirdPlace.getWinner());
		System.out.println("2018 FIFA World Cup Fourth Place: " + ThirdPlace.getLoser());*/
		
	}

}
